In [1]:
!pip install -q ydata-profiling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 1.9 MB/s eta 0:00:00


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-4/master/Data/Housing.csv')
data.shape

(546, 12)

In [4]:
data.head()

price  lotsize  bedrooms  bathrms  stories driveway recroom fullbase  \
0  42000.0     5850         3        1        2      yes      no      yes   
1  38500.0     4000         2        1        1      yes      no       no   
2  49500.0     3060         3        1        1      yes      no       no   
3  60500.0     6650         3        1        2      yes     yes       no   
4  61000.0     6360         2        1        1      yes      no       no   

  gashw airco  garagepl prefarea  
0    no    no         1       no  
1    no    no         0       no  
2    no    no         0       no  
3    no    no         0       no  
4    no    no         0       no

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64  
 2   bedrooms  546 non-null    int64  
 3   bathrms   546 non-null    int64  
 4   stories   546 non-null    int64  
 5   driveway  546 non-null    object 
 6   recroom   546 non-null    object 
 7   fullbase  546 non-null    object 
 8   gashw     546 non-null    object 
 9   airco     546 non-null    object 
 10  garagepl  546 non-null    int64  
 11  prefarea  546 non-null    object 
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB


In [6]:
data.describe()

price       lotsize    bedrooms     bathrms     stories  \
count     546.000000    546.000000  546.000000  546.000000  546.000000   
mean    68121.597070   5150.265568    2.965201    1.285714    1.807692   
std     26702.670926   2168.158725    0.737388    0.502158    0.868203   
min     25000.000000   1650.000000    1.000000    1.000000    1.000000   
25%     49125.000000   3600.000000    2.000000    1.000000    1.000000   
50%     62000.000000   4600.000000    3.000000    1.000000    2.000000   
75%     82000.000000   6360.000000    3.000000    2.000000    2.000000   
max    190000.000000  16200.000000    6.000000    4.000000    4.000000   

         garagepl  
count  546.000000  
mean     0.692308  
std      0.861307  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [7]:
data.skew(numeric_only=True)

price       1.209829
lotsize     1.322758
bedrooms    0.495872
bathrms     1.592096
stories     1.074657
garagepl    0.844808
dtype: float64

In [8]:
data["driveway"].unique()

array(['yes', 'no'], dtype=object)

In [9]:
data["recroom"].unique()

array(['no', 'yes'], dtype=object)

In [10]:
data["fullbase"].unique()

array(['yes', 'no'], dtype=object)

In [11]:
data["gashw"].unique()

array(['no', 'yes'], dtype=object)

In [12]:
data["airco"].unique()

array(['no', 'yes'], dtype=object)

In [13]:
data["garagepl"].unique()

array([1, 0, 2, 3])

In [14]:
data["prefarea"].unique()

array(['no', 'yes'], dtype=object)

In [15]:
data.duplicated().sum()

np.int64(1)

In [16]:
data.drop_duplicates(inplace=True)

In [17]:
data.shape

(545, 12)

In [18]:
data = pd.get_dummies(data=data,columns=['driveway','recroom','fullbase','gashw','airco','prefarea'],drop_first=True)

In [19]:
data.shape

(545, 12)

In [20]:
data.head()

price  lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  \
0  42000.0     5850         3        1        2         1          True   
1  38500.0     4000         2        1        1         0          True   
2  49500.0     3060         3        1        1         0          True   
3  60500.0     6650         3        1        2         0          True   
4  61000.0     6360         2        1        1         0          True   

   recroom_yes  fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
0        False          True      False      False         False  
1        False         False      False      False         False  
2        False         False      False      False         False  
3         True         False      False      False         False  
4        False         False      False      False         False

In [21]:
quantile33 = data['price'].quantile(0.33)
quantile66 = data['price'].quantile(0.66)
quantile100 = data['price'].quantile(1)

data['price_cat'] = pd.cut(data['price'],bins=[0,quantile33,quantile66,quantile100],labels=['Low','Medium','High'])
data.drop('price',axis=1,inplace=True)
print(f"data['price_cat'].value_counts :: {data['price_cat'].value_counts()}")

data['price_cat'].value_counts :: price_cat
High      184
Low       181
Medium    180
Name: count, dtype: int64


In [22]:
data.head()

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
0     5850         3        1        2         1          True        False   
1     4000         2        1        1         0          True        False   
2     3060         3        1        1         0          True        False   
3     6650         3        1        2         0          True         True   
4     6360         2        1        1         0          True        False   

   fullbase_yes  gashw_yes  airco_yes  prefarea_yes price_cat  
0          True      False      False         False       Low  
1         False      False      False         False       Low  
2         False      False      False         False       Low  
3         False      False      False         False    Medium  
4         False      False      False         False    Medium

## Model Building

In [23]:
x = data.drop('price_cat',axis=1)
y = data['price_cat']

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

print(f"x_train.shape ::: {x_train.shape}")
print(f"x_test.shape ::: {x_test.shape}")
print(f"y_train.shape ::: {y_train.shape}")
print(f"y_test.shape ::: {y_test.shape}")

x_train.shape ::: (381, 11)
x_test.shape ::: (164, 11)
y_train.shape ::: (381,)
y_test.shape ::: (164,)


In [25]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [26]:
y_train

array([0, 2, 0, 1, 0, 2, 1, 2, 2, 1, 1, 1, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1,
       1, 2, 0, 0, 2, 0, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 1, 2,
       2, 1, 1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 0, 2, 2, 2, 1, 2, 2, 1, 0, 1,
       1, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2,
       1, 2, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2,
       0, 2, 1, 1, 1, 2, 2, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 1, 2,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 2,
       0, 0, 1, 0, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 0, 0, 2, 1,
       2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 1, 0, 0, 0, 1,
       2, 1, 0, 1, 2, 1, 1, 2, 1, 0, 0, 0, 2, 2, 2,

In [27]:
y_test

array([0, 1, 0, 1, 2, 0, 2, 1, 0, 1, 2, 2, 2, 2, 0, 2, 2, 1, 2, 1, 1, 1,
       0, 1, 2, 1, 1, 1, 0, 2, 1, 0, 2, 1, 2, 1, 1, 2, 2, 0, 2, 0, 1, 1,
       2, 2, 1, 1, 2, 0, 1, 0, 1, 0, 1, 0, 0, 2, 2, 1, 2, 0, 2, 1, 1, 2,
       1, 2, 1, 2, 0, 0, 0, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 0, 1, 2, 2,
       1, 1, 2, 1, 0, 2, 1, 0, 1, 2, 0, 1, 2, 1, 2, 1, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 1, 0, 2, 1, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 2, 1,
       1, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0, 1, 2,
       0, 1, 1, 2, 0, 0, 2, 1, 2, 1])

In [28]:
lr = LogisticRegression(random_state=42,class_weight='balanced')
dt = DecisionTreeClassifier(random_state=42,class_weight='balanced')
rf = RandomForestClassifier(n_estimators=500,random_state=42,class_weight='balanced',n_jobs=-1)

In [29]:
gb = GradientBoostingClassifier(n_estimators=500,random_state=42)
xgb = xgb.XGBClassifier(n_estimators=500,random_state=42,num_class=3)

In [30]:
clf_list = [lr,dt,rf,gb,xgb]

In [31]:
train_scores = []
test_scores = []
clf_names = []
for clf in clf_list:
  clf.fit(x_train,y_train)
  train_scores.append(np.round(a=clf.score(x_train, y_train), decimals=2))
  test_scores.append(np.round(a=clf.score(x_test, y_test), decimals=2))
  clf_names.append(clf.__class__.__name__)
print('Success!')



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Success!


In [32]:
pd.DataFrame({'Classifier':clf_names,'Train Score':train_scores,'Test Score':test_scores})

Classifier  Train Score  Test Score
0          LogisticRegression         0.64        0.55
1      DecisionTreeClassifier         1.00        0.63
2      RandomForestClassifier         1.00        0.62
3  GradientBoostingClassifier         1.00        0.65
4               XGBClassifier         1.00        0.62

In [33]:
param_grid = {
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': list(range(3, 10))
}
gv = GridSearchCV(estimator=gb,param_grid=param_grid,cv=5,n_jobs=-1)
gv.fit(x_train,y_train)


GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(n_estimators=500,
                                                  random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9]})

In [34]:
best_model=gv.best_estimator_
best_model

GradientBoostingClassifier(learning_rate=0.01, n_estimators=500,
                           random_state=42)

In [35]:
best_params=gv.best_params_
best_params

{'learning_rate': 0.01, 'max_depth': 3}

In [36]:
best_model.fit(x_train,y_train)
y_pred_train = best_model.predict(x_train)
y_pred_test = best_model.predict(x_test)

In [37]:
best_model.score(x_train,y_pred_train)

1.0

In [38]:
best_model.score(x_test,y_pred_test)

1.0

In [39]:
x_train.head()

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
126     5960         3        3        2         1          True         True   
363    10700         3        1        2         0          True         True   
370     6360         3        1        1         2          True         True   
31      3500         4        1        2         2          True        False   
113     4260         4        1        2         0          True        False   

     fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
126          True      False      False         False  
363          True      False      False         False  
370          True      False       True          True  
31          False      False       True         False  
113          True      False       True         False

In [40]:
x_test.head()

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
316     5000         3        1        4         0          True        False   
77      3180         4        1        2         0          True        False   
360     6600         4        2        2         1          True         True   
90      6060         3        1        1         0          True         True   
493     8400         2        1        1         1          True        False   

     fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
316         False      False      False         False  
77           True      False       True         False  
360          True      False       True          True  
90           True      False      False         False  
493         False      False      False         False

In [41]:
x_train = x_train.applymap(lambda x: 1 if x is True else (0 if x is False else x))
x_test = x_test.applymap(lambda x: 1 if x is True else (0 if x is False else x))

/tmp/ipython-input-354208993.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  x_train = x_train.applymap(lambda x: 1 if x is True else (0 if x is False else x))
/tmp/ipython-input-354208993.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  x_test = x_test.applymap(lambda x: 1 if x is True else (0 if x is False else x))


In [42]:
x_train.head()

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
126     5960         3        3        2         1             1            1   
363    10700         3        1        2         0             1            1   
370     6360         3        1        1         2             1            1   
31      3500         4        1        2         2             1            0   
113     4260         4        1        2         0             1            0   

     fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
126             1          0          0             0  
363             1          0          0             0  
370             1          0          1             1  
31              0          0          1             0  
113             1          0          1             0

In [43]:
x_test.head()

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
316     5000         3        1        4         0             1            0   
77      3180         4        1        2         0             1            0   
360     6600         4        2        2         1             1            1   
90      6060         3        1        1         0             1            1   
493     8400         2        1        1         1             1            0   

     fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
316             0          0          0             0  
77              1          0          1             0  
360             1          0          1             1  
90              1          0          0             0  
493             0          0          0             0

In [44]:
x_train.columns

Index(['lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl', 'driveway_yes',
       'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes'],
      dtype='object')

In [45]:
new_data = {
'lotsize': 6000,
'bedrooms': 3,
'bathrms': 2,
'stories': 2,
'garagepl': 1,
'driveway_yes': 1,
'recroom_yes': 0,
'fullbase_yes': 0,
'gashw_yes': 0,
'airco_yes': 0,
'prefarea_yes': 0
}

In [46]:
new_data_df = pd.DataFrame([new_data])
new_data_df = new_data_df[x_train.columns]

In [47]:
new_data_df

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
0     6000         3        2        2         1             1            0   

   fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
0             0          0          0             0

In [51]:
new_pred = best_model.predict(new_data_df)
new_pred_proba = best_model.predict_proba(new_data_df)

In [49]:
new_pred_proba

array([[0.80125644, 0.0361264 , 0.16261716]])

In [52]:
print(f"Predicted class for madeup data row: {new_pred[0]}")

Predicted class for madeup data row: 0


In [55]:
class_labels = best_model.classes_
for i, label in enumerate(class_labels):
    print(f"Probability for class '{label}': {new_pred_proba[0][i]:.2f}")

Probability for class '0': 0.80
Probability for class '1': 0.04
Probability for class '2': 0.16
